# render.yaml
services:
  - type: web
    name: django-vuln
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: "gunicorn dojo.wsgi:application --bind 0.0.0.0:$PORT --workers 4"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString

  - type: database
    name: django-db
    engine: postgres
    version: 14